repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: observability
    createNamespace: true
    chart: grafana/grafana
    # สามารถระบุ version ของ chart ที่ต้องการได้ เช่น version: "7.3.7"
    values:
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.observability.svc.cluster.local
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki.observability.svc.cluster.local:3100
              access: proxy
            - name: Tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3100
              access: proxy
