repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: loki
    namespace: observability
    createNamespace: true
    chart: grafana/loki
    # สามารถระบุ version ของ chart ที่ต้องการได้ เช่น version: "5.42.2"
