repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: observability
    createNamespace: true
    chart: prometheus-community/prometheus
    # สามารถระบุ version ของ chart ที่ต้องการได้ เช่น version: "25.11.0"
