repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: observability
    createNamespace: true
    chart: grafana/tempo
    # สามารถระบุ version ของ chart ที่ต้องการได้ เช่น version: "1.7.2"
